FROM node:22-alpine
WORKDIR /app
RUN apk add --no-cache ffmpeg
RUN corepack enable
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY shared/package.json shared/
COPY backend/package.json backend/
RUN pnpm install --filter @alanya-holidays/backend... --no-frozen-lockfile
COPY . .
EXPOSE 4000
WORKDIR /app/backend
CMD ["pnpm", "run", "start:dev"]
