import type { TrustBadgeType } from "@/components/common/TrustBadge";

export interface Business {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  description: string;
  address: string;
  phone: string;
  email: string;
  website: string;
  /** Rating imported from Google. Kept distinct from Alanya Holidays reviews. */
  googleRating?: number | null;
  /** Review count reported by Google, not an Alanya Holidays review count. */
  googleReviewCount?: number | null;
  rating: number;
  reviewCount: number;
  image: string;
  tags: string[];
  featured: boolean;
  trustBadge?: TrustBadgeType;
  priceRange: string;
  openingHours?: string;
  lat?: number;
  lng?: number;
  is_claimed?: boolean;
  is_verified?: boolean;
  claimed_at?: string;
  can_claim?: boolean;
  status?: string;
  tier?: string;
}

export const businessCategories = [
  { id: "all", name: "All Businesses", icon: "ri-store-2-line" },
  { id: "restaurants-cafes", name: "Restaurants & Cafés", icon: "ri-restaurant-2-line" },
  { id: "hotels-accommodation", name: "Hotels & Accommodation", icon: "ri-hotel-line" },
  { id: "tours-activities", name: "Tours & Activities", icon: "ri-ship-line" },
  { id: "real-estate", name: "Real Estate", icon: "ri-home-4-line" },
  { id: "car-rental", name: "Car & Scooter Rental", icon: "ri-car-line" },
  { id: "health-wellness", name: "Health & Wellness", icon: "ri-heart-pulse-line" },
  { id: "shopping", name: "Shopping", icon: "ri-shopping-bag-3-line" },
  { id: "services", name: "Professional Services", icon: "ri-briefcase-line" },
  { id: "nightlife", name: "Nightlife & Bars", icon: "ri-goblet-line" },
];

export const businesses: Business[] = [
  {
    id: "biz-001",
    name: "Kale Panorama Restaurant",
    category: "restaurants-cafes",
    subcategory: "Turkish Cuisine",
    description: "Perched on the hillside beneath Alanya Castle, Kale Panorama offers authentic Ottoman and Mediterranean cuisine with breathtaking 180-degree views of the coastline. Famous for their slow-cooked lamb tandir and fresh seafood mezes, served on a candlelit terrace overlooking the harbor.",
    address: "Hisariçi Mahallesi, Kale Yolu 42, 07400 Alanya/Antalya",
    phone: "+90 242 513 44 21",
    email: "reservations@kalepanorama.com",
    website: "https://kalepanorama.com",
    rating: 4.8,
    reviewCount: 347,
    image: "/images/placeholder-business.svg",
    tags: ["Turkish Cuisine", "Seafood", "Fine Dining", "Rooftop", "Sunset Views", "Romantic"],
    featured: true,
    trustBadge: "Signature Collection",
    priceRange: "$$$",
    openingHours: "12:00 - 23:00, Closed Mondays",
    lat: 36.5361,
    lng: 31.9956,
  },
  {
    id: "biz-002",
    name: "Cleopatra Beach Club",
    category: "restaurants-cafes",
    subcategory: "Beach Club",
    description: "The most iconic beach club on Cleopatra Beach, offering sun loungers, cabanas, water sports, and a full-service restaurant right on the golden sand. Their wood-fired pizzas and frozen cocktails are legendary among returning visitors. Live DJ sets every Saturday during summer.",
    address: "Güller Pınarı Mahallesi, Cleopatra Beach, 07400 Alanya/Antalya",
    phone: "+90 242 522 18 90",
    email: "info@cleopatrabeachclub.com",
    website: "https://cleopatrabeachclub.com",
    rating: 4.6,
    reviewCount: 892,
    image: "/images/placeholder-business.svg",
    tags: ["Beach Club", "Pizza", "Cocktails", "Water Sports", "Live Music", "Family-Friendly"],
    featured: true,
    trustBadge: "Top Rated Destination Partner",
    priceRange: "$$",
    openingHours: "09:00 - 01:00, Daily",
    lat: 36.5489,
    lng: 31.9908,
  },
  {
    id: "biz-003",
    name: "Mezze Garden Café",
    category: "restaurants-cafes",
    subcategory: "Café & Breakfast",
    description: "A hidden gem tucked away in a lush courtyard garden in the old town, Mezze Garden Café serves the most elaborate Turkish breakfast spreads in Alanya. Over 40 varieties of homemade jams, cheeses, olives, and pastries. Their gözleme, made fresh by local village women, is worth the visit alone.",
    address: "Tophane Mahallesi, Andızlı Camii Sokak 8, 07400 Alanya/Antalya",
    phone: "+90 242 511 33 67",
    email: "hello@mezzegarden.com",
    website: "https://mezzegarden.com",
    rating: 4.9,
    reviewCount: 423,
    image: "/images/placeholder-business.svg",
    tags: ["Turkish Breakfast", "Garden Café", "Gözleme", "Vegetarian-Friendly", "Cozy", "Old Town"],
    featured: true,
    trustBadge: "Local Favorite",
    priceRange: "$$",
    openingHours: "08:00 - 20:00, Daily",
    lat: 36.5375,
    lng: 31.9972,
  },
  {
    id: "biz-004",
    name: "Alanya Marina Boutique Hotel",
    category: "hotels-accommodation",
    subcategory: "Boutique Hotel",
    description: "A beautifully restored Ottoman mansion turned boutique hotel, just steps from the harbor. Each of the 12 rooms is uniquely decorated with hand-painted tiles and antique furnishings. The rooftop infinity pool and champagne bar are open exclusively to guests, offering uninterrupted views of the castle and sea.",
    address: "İskele Caddesi 24, 07400 Alanya/Antalya",
    phone: "+90 242 519 88 11",
    email: "stay@alanyamarinahotel.com",
    website: "https://alanyamarinahotel.com",
    rating: 4.7,
    reviewCount: 286,
    image: "/images/placeholder-business.svg",
    tags: ["Boutique Hotel", "Rooftop Pool", "Ottoman Architecture", "Harbor Views", "Adults-Only"],
    featured: true,
    trustBadge: "Recommended by Travellers",
    priceRange: "$$$",
    openingHours: "24/7 Reception",
    lat: 36.5347,
    lng: 31.9981,
  },
  {
    id: "biz-005",
    name: "Villa Sevilla Resort",
    category: "hotels-accommodation",
    subcategory: "All-Inclusive Resort",
    description: "A sprawling 5-star all-inclusive resort set on 40 acres of tropical gardens with a private beach. Seven restaurants, five pools including an adults-only infinity pool, a world-class spa, and daily activities from yoga to paddleboarding. Ideal for families with their award-winning kids club.",
    address: "Konaklı Mahallesi, Sahil Caddesi 78, 07490 Alanya/Antalya",
    phone: "+90 242 565 20 00",
    email: "reservations@villasevilla.com",
    website: "https://villasevilla.com",
    rating: 4.5,
    reviewCount: 1203,
    image: "/images/placeholder-business.svg",
    tags: ["All-Inclusive", "5-Star", "Private Beach", "Spa", "Family Resort", "Kids Club"],
    featured: true,
    trustBadge: "Trusted by Travellers",
    priceRange: "$$$",
    openingHours: "24/7 Reception",
    lat: 36.5844,
    lng: 31.9055,
  },
  {
    id: "biz-006",
    name: "Alanya Pirate Boat Tours",
    category: "tours-activities",
    subcategory: "Boat Tours",
    description: "The original pirate-themed boat tour of Alanya, sailing daily from the harbor. Explore hidden caves, swim in the famous Phosphorus Cave, visit the Lovers Cave, and enjoy a foam party on the open deck. Full-day trip includes lunch, unlimited soft drinks, and hotel transfers. The most photographed boat in the marina.",
    address: "Alanya Harbor, İskele Caddesi, 07400 Alanya/Antalya",
    phone: "+90 532 441 78 92",
    email: "ahoy@alanyapirateboats.com",
    website: "https://alanyapirateboats.com",
    rating: 4.7,
    reviewCount: 567,
    image: "/images/placeholder-business.svg",
    tags: ["Boat Tour", "Swimming", "Caves", "Family-Friendly", "Lunch Included", "Full-Day Trip"],
    featured: true,
    trustBadge: "Curated Experience",
    priceRange: "$$",
    openingHours: "Daily departures 10:00 - 16:00",
    lat: 36.5353,
    lng: 31.9978,
  },
  {
    id: "biz-007",
    name: "Taurus Mountain Safari",
    category: "tours-activities",
    subcategory: "Adventure Tours",
    description: "An adrenaline-packed 4x4 jeep safari into the majestic Taurus Mountains. Cross rivers, visit traditional nomadic Yörük villages, swim in natural pools beneath waterfalls, and enjoy a barbecue lunch in the pine forest. Professional multilingual guides share stories about the region's flora, fauna, and folklore.",
    address: "Pickup from all Alanya hotels, 07400 Alanya/Antalya",
    phone: "+90 544 672 31 45",
    email: "adventure@taurussafari.com",
    website: "https://taurussafari.com",
    rating: 4.8,
    reviewCount: 312,
    image: "/images/placeholder-business.svg",
    tags: ["4x4 Safari", "Jeep Tour", "Waterfalls", "Swimming", "BBQ Lunch", "Cultural"],
    featured: false,
    trustBadge: "Curated Experience",
    priceRange: "$$",
    openingHours: "Daily tours 08:30 - 17:30",
    lat: 36.5436,
    lng: 31.9997,
  },
  {
    id: "biz-008",
    name: "Damlataş Hamam & Spa",
    category: "health-wellness",
    subcategory: "Turkish Bath",
    description: "A traditional Turkish bath experience in a beautifully restored 16th-century hamam near Damlataş Cave. Their signature package includes a steam room session, full body scrub with handmade olive oil soap, foam massage, and aromatherapy oil massage. Separate sections for men and women, with professional therapists trained in Ottoman techniques.",
    address: "Damlataş Caddesi 15, 07400 Alanya/Antalya",
    phone: "+90 242 512 44 33",
    email: "relax@damlatashamam.com",
    website: "https://damlatashamam.com",
    rating: 4.6,
    reviewCount: 478,
    image: "/images/placeholder-business.svg",
    tags: ["Turkish Bath", "Hamam", "Massage", "Spa", "Historical", "Couples-Friendly"],
    featured: false,
    trustBadge: "Verified Experience",
    priceRange: "$$",
    openingHours: "09:00 - 22:00, Daily",
    lat: 36.5447,
    lng: 32.0035,
  },
  {
    id: "biz-009",
    name: "Mediterranean Smile Dental Clinic",
    category: "health-wellness",
    subcategory: "Dental Clinic",
    description: "Award-winning dental clinic specializing in cosmetic dentistry, implants, and Hollywood smiles. Equipped with the latest 3D scanning and CAD/CAM technology. Popular with international patients — they provide airport transfers, hotel arrangements, and multilingual coordinators for a seamless medical tourism experience.",
    address: "Atatürk Caddesi 142, Kat 4, 07400 Alanya/Antalya",
    phone: "+90 242 519 77 55",
    email: "smile@mediterraneandental.com",
    website: "https://mediterraneandental.com",
    rating: 4.9,
    reviewCount: 821,
    image: "/images/placeholder-business.svg",
    tags: ["Dental Clinic", "Cosmetic Dentistry", "Implants", "Medical Tourism", "English-Speaking"],
    featured: false,
    trustBadge: "Top Rated Destination Partner",
    priceRange: "$$$",
    openingHours: "09:00 - 18:00, Mon-Sat",
    lat: 36.5545,
    lng: 32.0110,
  },
  {
    id: "biz-010",
    name: "Alanya Property Experts",
    category: "real-estate",
    subcategory: "Real Estate Agency",
    description: "The most trusted real estate agency in Alanya with over 15 years of experience helping foreigners buy property in Turkey. Specializing in sea-view apartments, luxury villas, and investment properties. Their multilingual team handles everything from property search to title deed transfer, citizenship applications, and after-sales management.",
    address: "Oba Mahallesi, D400 Caddesi 88, 07400 Alanya/Antalya",
    phone: "+90 242 514 22 11",
    email: "buy@alanyapropertyexperts.com",
    website: "https://alanyapropertyexperts.com",
    rating: 4.7,
    reviewCount: 234,
    image: "/images/placeholder-business.svg",
    tags: ["Real Estate", "Property Sales", "Citizenship", "English-Speaking", "Investment"],
    featured: true,
    trustBadge: "Trusted by Travellers",
    priceRange: "$$$",
    openingHours: "09:00 - 19:00, Mon-Fri; 10:00 - 16:00, Sat",
    lat: 36.5560,
    lng: 32.0150,
  },
  {
    id: "biz-011",
    name: "Sunset Rent a Car",
    category: "car-rental",
    subcategory: "Car Rental",
    description: "Family-run car rental with transparent pricing and no hidden fees. Fleet ranges from economy hatchbacks to luxury SUVs and convertibles. Free delivery and pickup to any Alanya hotel or the Gazipaşa Airport. All rentals include comprehensive insurance, 24/7 roadside assistance, and unlimited mileage.",
    address: "Güller Pınarı Mahallesi, Hacet Caddesi 34, 07400 Alanya/Antalya",
    phone: "+90 532 123 88 77",
    email: "drive@sunsetrentacar.com",
    website: "https://sunsetrentacar.com",
    rating: 4.8,
    reviewCount: 156,
    image: "/images/placeholder-business.svg",
    tags: ["Car Rental", "Airport Transfer", "Scooter Rental", "Insurance Included", "24/7 Support"],
    featured: false,
    trustBadge: "Verified Experience",
    priceRange: "$$",
    openingHours: "08:00 - 22:00, Daily",
    lat: 36.5498,
    lng: 32.0085,
  },
  {
    id: "biz-012",
    name: "Alanya Gold Bazaar",
    category: "shopping",
    subcategory: "Jewelry & Gold",
    description: "A family legacy spanning three generations, Alanya Gold Bazaar is the premier destination for handcrafted Turkish gold jewelry, diamonds, and precious stones. Every piece comes with a certified guarantee. They specialize in custom designs — describe your dream piece and their master jeweler will bring it to life within days.",
    address: "Şekerhane Mahallesi, Tevfikiye Caddesi 12, 07400 Alanya/Antalya",
    phone: "+90 242 511 66 99",
    email: "gold@alanyagoldbazaar.com",
    website: "https://alanyagoldbazaar.com",
    rating: 4.5,
    reviewCount: 189,
    image: "/images/placeholder-business.svg",
    tags: ["Jewelry", "Gold", "Custom Design", "Diamonds", "Certified", "Family Business"],
    featured: false,
    trustBadge: "Recommended by Travellers",
    priceRange: "$$$",
    openingHours: "10:00 - 20:00, Mon-Sat",
    lat: 36.5455,
    lng: 32.0012,
  },
  {
    id: "biz-013",
    name: "Anatolian Carpet Gallery",
    category: "shopping",
    subcategory: "Carpets & Textiles",
    description: "Step into a world of color and craftsmanship. Anatolian Carpet Gallery showcases handwoven Turkish and Persian carpets, kilims, and silk textiles sourced directly from village cooperatives across Anatolia. Every carpet comes with a certificate of authenticity. They offer worldwide insured shipping and complimentary tea while you browse.",
    address: "Damlataş Caddesi 45, 07400 Alanya/Antalya",
    phone: "+90 242 513 88 22",
    email: "carpets@anatoliangallery.com",
    website: "https://anatoliangallery.com",
    rating: 4.7,
    reviewCount: 134,
    image: "/images/placeholder-business.svg",
    tags: ["Carpets", "Kilims", "Handwoven", "Silk", "Worldwide Shipping", "Authentic"],
    featured: false,
    trustBadge: "Local Favorite",
    priceRange: "$$$",
    openingHours: "09:30 - 19:30, Daily",
    lat: 36.5438,
    lng: 32.0028,
  },
  {
    id: "biz-014",
    name: "Alanya Legal Consulting",
    category: "services",
    subcategory: "Legal Services",
    description: "Bilingual law firm specializing in Turkish property law, residence permits, citizenship by investment, company formation, and contract review. Their English-speaking lawyers have helped over 2,000 expats and investors navigate Turkish bureaucracy smoothly. Fixed-fee packages available with no hidden charges.",
    address: "Oba Mahallesi, Atatürk Caddesi 210, Kat 3, 07400 Alanya/Antalya",
    phone: "+90 242 518 44 66",
    email: "info@alanyalegal.com",
    website: "https://alanyalegal.com",
    rating: 4.8,
    reviewCount: 267,
    image: "/images/placeholder-business.svg",
    tags: ["Legal Services", "Property Law", "Residence Permit", "Citizenship", "English-Speaking"],
    featured: false,
    trustBadge: "Trusted by Travellers",
    priceRange: "$$$",
    openingHours: "09:00 - 18:00, Mon-Fri",
    lat: 36.5555,
    lng: 32.0135,
  },
  {
    id: "biz-015",
    name: "Blue Wave Translation",
    category: "services",
    subcategory: "Translation Services",
    description: "Certified translation and interpretation services in over 20 languages, with a focus on legal, medical, and real estate documents. Notarized translations for official use accepted by all Turkish government offices. Same-day service available for urgent documents. Also offers sworn interpretation for court and hospital visits.",
    address: "Şekerhane Mahallesi, Hükümet Caddesi 67, 07400 Alanya/Antalya",
    phone: "+90 242 510 33 11",
    email: "translate@bluewave.com",
    website: "https://bluewavetranslation.com",
    rating: 4.9,
    reviewCount: 98,
    image: "/images/placeholder-business.svg",
    tags: ["Translation", "Interpretation", "Notarized", "Legal Documents", "Medical Translation"],
    featured: false,
    trustBadge: "Verified Experience",
    priceRange: "$$",
    openingHours: "09:00 - 18:00, Mon-Fri; 10:00 - 14:00, Sat",
    lat: 36.5460,
    lng: 32.0005,
  },
  {
    id: "biz-016",
    name: "Harbour Nights Club",
    category: "nightlife",
    subcategory: "Nightclub",
    description: "Alanya's premier nightlife destination, set in a converted stone warehouse right on the harbor. Two floors of music — R&B and hip-hop upstairs, house and techno in the basement. International DJs every weekend, an extensive cocktail menu, and VIP bottle service. The outdoor terrace is perfect for cooling off between dance sessions.",
    address: "İskele Caddesi 55, 07400 Alanya/Antalya",
    phone: "+90 535 789 44 22",
    email: "party@harbournights.com",
    website: "https://harbournights.com",
    rating: 4.3,
    reviewCount: 412,
    image: "/images/placeholder-business.svg",
    tags: ["Nightclub", "DJ", "Cocktails", "VIP Service", "Harbor Location", "Late Night"],
    featured: false,
    trustBadge: "Signature Collection",
    priceRange: "$$$",
    openingHours: "22:00 - 04:00, Wed-Sun",
    lat: 36.5349,
    lng: 31.9976,
  },
  {
    id: "biz-017",
    name: "Rooftop 42 Bar",
    category: "nightlife",
    subcategory: "Rooftop Bar",
    description: "Perched on the 7th floor with the best panoramic view of Alanya Castle illuminated at night. Rooftop 42 serves craft cocktails, premium wines, and a curated tapas menu. The resident saxophonist plays live every Thursday and Friday evening. Dress code is smart casual — this is where Alanya comes to see and be seen.",
    address: "Atatürk Caddesi 140, Kat 7, 07400 Alanya/Antalya",
    phone: "+90 242 519 42 42",
    email: "cheers@rooftop42.com",
    website: "https://rooftop42.com",
    rating: 4.6,
    reviewCount: 203,
    image: "/images/placeholder-business.svg",
    tags: ["Rooftop Bar", "Craft Cocktails", "Live Music", "Tapas", "Castle Views", "Upscale"],
    featured: false,
    trustBadge: "Signature Collection",
    priceRange: "$$$",
    openingHours: "17:00 - 02:00, Daily",
    lat: 36.5520,
    lng: 32.0090,
  },
  {
    id: "biz-018",
    name: "Green Valley Apart Hotel",
    category: "hotels-accommodation",
    subcategory: "Apart Hotel",
    description: "A peaceful apart hotel nestled in lush gardens in the Oba district, just 300 meters from the beach. Each apartment features a fully equipped kitchen, private balcony, and air conditioning. The complex boasts two swimming pools, a children's playground, and a barbecue area. Perfect for families and long-stay travelers seeking a home-away-from-home.",
    address: "Oba Mahallesi, Çiçek Sokak 15, 07400 Alanya/Antalya",
    phone: "+90 242 514 77 33",
    email: "stay@greenvalleyaparthotel.com",
    website: "https://greenvalleyaparthotel.com",
    rating: 4.4,
    reviewCount: 178,
    image: "/images/placeholder-business.svg",
    tags: ["Apart Hotel", "Swimming Pool", "Family-Friendly", "Kitchen", "Long Stay", "Garden"],
    featured: false,
    trustBadge: "Trusted by Travellers",
    priceRange: "$$",
    openingHours: "24/7 Reception",
    lat: 36.5580,
    lng: 32.0180,
  },
  {
    id: "biz-019",
    name: "Elysium Spa & Wellness",
    category: "health-wellness",
    subcategory: "Spa & Wellness Center",
    description: "A sanctuary of calm in the heart of Alanya, Elysium offers holistic wellness treatments including Thai massage, hot stone therapy, reflexology, and aromatherapy. Their signature 3-hour 'Journey to Serenity' package combines a traditional Turkish bath ritual with a deep tissue massage and facial. Private couples treatment rooms available.",
    address: "Oba Mahallesi, Yaşar Doğu Caddesi 28, 07400 Alanya/Antalya",
    phone: "+90 242 518 99 00",
    email: "bliss@elysiumspa.com",
    website: "https://elysiumspa.com",
    rating: 4.7,
    reviewCount: 321,
    image: "/images/placeholder-business.svg",
    tags: ["Spa", "Massage", "Wellness", "Couples Treatments", "Thai Massage", "Aromatherapy"],
    featured: false,
    trustBadge: "Signature Collection",
    priceRange: "$$$",
    openingHours: "10:00 - 21:00, Daily",
    lat: 36.5565,
    lng: 32.0140,
  },
  {
    id: "biz-020",
    name: "Alanya Diving Center",
    category: "tours-activities",
    subcategory: "Scuba Diving",
    description: "PADI 5-star dive center offering daily boat dives to over 15 spectacular sites along the Alanya coast. Explore underwater caves, shipwrecks, and vibrant reefs teeming with Mediterranean marine life. Full PADI certification courses from Open Water to Divemaster available. All equipment provided, with small group sizes for maximum safety.",
    address: "Alanya Harbor, East Pier, 07400 Alanya/Antalya",
    phone: "+90 533 256 44 88",
    email: "dive@alanyadiving.com",
    website: "https://alanyadiving.com",
    rating: 4.9,
    reviewCount: 145,
    image: "/images/placeholder-business.svg",
    tags: ["Scuba Diving", "PADI Courses", "Shipwrecks", "Caves", "Equipment Included", "Small Groups"],
    featured: false,
    trustBadge: "Curated Experience",
    priceRange: "$$$",
    openingHours: "08:00 - 18:00, Daily (April-November)",
    lat: 36.5345,
    lng: 31.9965,
  },
  {
    id: "biz-021",
    name: "Scoot Alanya",
    category: "car-rental",
    subcategory: "Scooter Rental",
    description: "The easiest way to zip around Alanya. Scoot Alanya rents modern 50cc and 125cc scooters by the day, week, or month. All scooters are under 2 years old, regularly serviced, and come with two helmets, a phone holder, and a lock. No deposit required for weekly rentals. Free delivery anywhere in Alanya center.",
    address: "Saray Mahallesi, Yunus Emre Caddesi 19, 07400 Alanya/Antalya",
    phone: "+90 536 441 22 33",
    email: "ride@scootalanya.com",
    website: "https://scootalanya.com",
    rating: 4.5,
    reviewCount: 267,
    image: "/images/placeholder-business.svg",
    tags: ["Scooter Rental", "Helmet Included", "Free Delivery", "Daily Rental", "Weekly Rental"],
    featured: false,
    trustBadge: "Local Favorite",
    priceRange: "$",
    openingHours: "09:00 - 19:00, Daily",
    lat: 36.5500,
    lng: 32.0055,
  },
  {
    id: "biz-022",
    name: "The Spice Bazaar",
    category: "shopping",
    subcategory: "Spices & Gourmet",
    description: "A feast for the senses. The Spice Bazaar stocks over 200 varieties of Turkish spices, dried herbs, teas, lokum (Turkish delight), nuts, and organic olive oils sourced from family farms across Anatolia. The aroma alone will draw you in. They vacuum-pack everything for travel and offer tasting sessions for the undecided.",
    address: "Şekerhane Mahallesi, Kapalı Çarşı İçi 22, 07400 Alanya/Antalya",
    phone: "+90 242 511 55 44",
    email: "flavors@thespicebazaar.com",
    website: "https://thespicebazaar.com",
    rating: 4.8,
    reviewCount: 312,
    image: "/images/placeholder-business.svg",
    tags: ["Spices", "Turkish Delight", "Olive Oil", "Tea", "Gourmet", "Gifts"],
    featured: false,
    trustBadge: "Local Favorite",
    priceRange: "$$",
    openingHours: "09:00 - 20:00, Daily",
    lat: 36.5458,
    lng: 32.0020,
  },
  {
    id: "biz-023",
    name: "Paraglide Alanya",
    category: "tours-activities",
    subcategory: "Paragliding",
    description: "Soar like an eagle over the stunning Alanya coastline. Tandem paragliding flights launch from 700 meters above sea level, offering 20-30 minutes of pure adrenaline with panoramic views of the castle, Cleopatra Beach, and the entire bay. Professional licensed pilots with over 10,000 combined flights. GoPro video and photos included in the price.",
    address: "Launch site pickup from all Alanya hotels, 07400 Alanya/Antalya",
    phone: "+90 541 889 55 77",
    email: "fly@paraglidealanya.com",
    website: "https://paraglidealanya.com",
    rating: 4.9,
    reviewCount: 198,
    image: "/images/placeholder-business.svg",
    tags: ["Paragliding", "Tandem Flight", "GoPro Included", "Adventure", "Coastal Views"],
    featured: false,
    trustBadge: "Curated Experience",
    priceRange: "$$$",
    openingHours: "Daily flights 09:00 - 18:00 (weather permitting)",
    lat: 36.5380,
    lng: 31.9930,
  },
  {
    id: "biz-024",
    name: "Sultan's Kebab House",
    category: "restaurants-cafes",
    subcategory: "Kebab Restaurant",
    description: "No trip to Turkey is complete without a proper kebab, and Sultan's is where the locals go. Their Adana kebab and İskender are legendary, cooked over charcoal and served with fresh lavaş bread straight from the stone oven. Unpretentious, affordable, and absolutely delicious — the lines out the door at dinner speak for themselves.",
    address: "Saray Mahallesi, Atatürk Caddesi 85, 07400 Alanya/Antalya",
    phone: "+90 242 512 66 33",
    email: "eat@sultanskebab.com",
    website: "https://sultanskebab.com",
    rating: 4.7,
    reviewCount: 534,
    image: "/images/placeholder-business.svg",
    tags: ["Kebab", "Turkish Cuisine", "Casual Dining", "Local Favorite", "Charcoal Grill", "Affordable"],
    featured: false,
    trustBadge: "Local Favorite",
    priceRange: "$",
    openingHours: "11:00 - 23:00, Daily",
    lat: 36.5510,
    lng: 32.0070,
  },
];
